# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "test-app-youp"
client_id = "6c3eb35f02d0ae0eb3961bf5420e5ac2"
application_url = "https://bf26-94-247-4-243.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://bf26-94-247-4-243.ngrok-free.app/auth/tokens",
  "https://bf26-94-247-4-243.ngrok-free.app/auth/callback"
]

[webhooks]
api_version = "2023-07"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://bf26-94-247-4-243.ngrok-free.app/gdpr/customers_redact"
  customer_data_request_url = "https://bf26-94-247-4-243.ngrok-free.app/gdpr/customers_data_request"
  shop_deletion_url = "https://bf26-94-247-4-243.ngrok-free.app/gdpr/shop_redact"

[app_proxy]
url = "https://bf26-94-247-4-243.ngrok-free.app/express-proxy"
subpath = "express-proxy"
prefix = "apps"

[pos]
embedded = false
